apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ledshim
  namespace: default
  labels:
    app: ledshim
    ledshim: true
spec:
  selector:
    matchLabels:
      name: ledshim
  template:
    metadata:
      labels:
        name: ledshim
        ledshim: true
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        ledshim: true
      containers:
      - name: ledshim
        image: bartbrinkman/homelab-ledshim:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 10
