apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-client-provisioner/deployment.yaml
  - nfs-client-provisioner/rbac.yaml
  - nfs-client-provisioner/storage-class.yaml