apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: quay.io/external_storage/nfs-client-provisioner-arm
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "false"