apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: quay.io/nfs-client-provisioner
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "false"
