apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: default
spec:
  interval: 1m
  timeout: 30m
  chart:
    spec:
      chart: heimdall
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: heimdall
        namespace: default
  values:
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: heimdall.k3s
          paths:
            - path: /
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: managed-nfs-storage
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
                        