apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gonic
  namespace: default
spec:
  interval: 1m
  timeout: 30m
  chart:
    spec:
      chart: gonic
      sourceRef:
        kind: HelmRepository
        name: gonic
        namespace: default
  values:
    image:
      tag: v0.12.2
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: gonic.k3s.bartbrinkman.nl
          paths:
            - path: /
      tls:
        - hosts:
            - gonic.k3s.bartbrinkman.nl
          secretName: gonic-k3s-bartbrinkman-nl-tls
    persistence:
      data:
        enabled: true
        storageClass: managed-nfs-storage
        accessMode: ReadWriteOnce
        size: 1Gi
      music:
        enabled: true
        storageClass: managed-nfs-storage
        accessMode: ReadWriteOnce
        size: 100Gi
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
                        