apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: default
      interval: 10m
  values:
    installCRDs: true
    